nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:4200']
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'X-Requested-With']
        allow_methods: ['OPTIONS', 'GET', 'POST', 'PUT', 'DELETE', 'PATCH']
        expose_headers: ['X-Liste-Libelle']
        max_age: 3600

    paths:
        '^/api/':
            allow_origin: ['http://localhost:4200']
            allow_headers: ['Content-Type', 'Authorization', 'Accept', 'X-Requested-With']
            allow_methods: ['OPTIONS', 'GET', 'POST', 'PUT', 'DELETE', 'PATCH']
            expose_headers: ['X-Liste-Libelle']
            max_age: 3600
